tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask"
# brew "gnupg"
brew "go"
brew "hugo"
brew "nginx"
brew "node"
# brew "unrar"
cask "visual-studio-code"
cask "google-chrome"
cask "iterm2"
cask "sublime-merge"
cask "docker"
